FROM envoyproxy/envoy-dev:latest
ADD lua/apisix/ /apisix/
COPY compose/envoy.yaml /etc/envoy.yaml
RUN chmod go+r /etc/envoy.yaml /apisix/core.lua
CMD /usr/local/bin/envoy -c /etc/envoy.yaml -l debug --service-cluster proxy
